server:
  port: 8888

spring:
  #Cau hinh co so du lieu
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/webtoeic
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  #Cau hinh dang nhap oauth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile

        provider:
          facebook:
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture

  #Cau hinh upload files
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB

  #Cau hinh duong dan file anh, audio
  web:
    resources:
      static-locations[0]: file:src/main/resources/static/
      static-locations[1]: classpath:/static/

 # Cau hinh gui mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:lecthanh232002@gmail.com}
    password: ${MAIL_PASSWORD:ygaphwwjwpyxwrjca}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  #Cau hinh domain cua front-end
  domain:
    front-end: ${DOMAIN_FE:http://localhost:3000}

  # Cau hinh redis
  data:
    redis:
      host: ${HOST_REDIS:localhost}
      port: ${PORT_REDIS:6379}

  # Cau hinh elastic-search
  elasticsearch:
    uris: http://localhost:9200


# Cau hinh JWT
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:ezDniu6kzUCCwd0RCZLcmm9sF9erh2AXvISijgrdCPk}
    at-expiration-ms: 86400000
    rt-expiration-ms: 2592000000

#Cau hinh duong dan luu anh
app:
  baseImageUrl: http://localhost:8888/
  upload:
    dir: src/main/resources/images

#Cau hinh swagger open api
open:
  api:
    title: Test API BE-Web Toeic
    version: 1.0.0
    description: This is description
    urlServer: http://localhost:8888
    serverName: Server Test